### ISSUE TITLE
RSS podcast order setting

### ISSUE THREAD

**Issue by giupi** [BabDev/Podcast-Manager#170]
Hello,

I need to show some podcasts in a given order; so I started to create them from the last to the first so that the first is displayed at the beginning in the module (since in the module there is no way to set the listing order, unlike the menu item in which I can set the order).

Now the problem arises in the rss link, since the rss shows the first created at the beginning (but the first created is supposed to be the last showing).

To be more clear:

I created the podcasts in this order: C, B, A, so the module shows A, B, C; but this way the RSS shows C, B, A 

Is there any parameter to add to the rss link so that I could get a reverse order so it could show ABC?

http://www..../component/podcastmanager/?format=raw&feedname=3

I tried to add "&order=ASC", "&order=DESC", "&order=ascending", "&order=1" and many other combinations, without any result...

Thanks for your help

PS My version is 2.1.0 on Joomla 3.3.1

**Comment by AwakeningNC** [comment]
I am also RockinRobbins04, I forgot the login...anyways, I don't see where to change this, I just updated to 2.2. beta.

Thanks!

**Comment by mbabker** [comment]
If you have a menu item set up for the RSS feed, the options will be on the menu item's edit screen.  Otherwise, you would need to manually add the strings to your feed URL.
