### ISSUE TITLE
Issues after 3.3.3 Update

### ISSUE THREAD

**Issue by zgoodman** [BabDev/Podcast-Manager#182]
Hello,

We've had some issues after updating Joomla from 3.0.3 to 3.3.3. We did a server change at the same time, so it's possible some of them are server setting related, and not specific to Podcast Manager.

First, our RSS feed is no longer formed as valid XML. Here's a link:
http://620ckrm.com/podcasts?format=raw&feedname=1

I tried updating to the latest version of Podcast Manager in Joomla, but it said we were already up to date. After trying the update, I can no longer use the File Manager. It gives this error:
500 JHtmlBehavior::uploader not found. 

Any ideas? Thank you!

**Comment by mbabker** [comment]
Were you able to get this sorted?  IIRC JHtmlBehavior::uploader was removed as a security risk somewhere in the Joomla 3.2 releases which means if you were using the Flash based media uploader, that would no longer work.  The File Manager should be inheriting that option from the core Media Manager, so make sure that is set up properly.
