### ISSUE TITLE
Invalid RSS Feed?

### ISSUE THREAD

**Issue by numinousmedia** [BabDev/Podcast-Manager#184]
One of my clients let me know that their podcast was no longer showing up in iTunes. I checked into it, and it does look to be the case. 

They are running Joomla 2.5.24, with Podcast Manager 2.1.0. When I take a look at the raw feed (http://www.phbchurch.com/phbc-sermon-rss?feedname=3&limit=0&format=raw), it doesn't look like there are any actual media files available for playing. The normal page podcast feed page is working fine (http://www.phbchurch.com/resources/listen-to-sermons).

Any ideas what's happening here? I appreciate your help, as always. Thanks!

- Ryan

**Comment by mbabker** [comment]
I've looked at this a couple of times and aside from the Google Chrome RSS extension I have not listing all of the items, everything seems to look right.
