### ISSUE TITLE
Feed only shows 4

### ISSUE THREAD

**Issue by AwakeningNC** [BabDev/Podcast-Manager#185]
I have published my feed and everything. I see no options on how many to limit the feed too. I have 6 published episodes but only 4 show up on my RSS. Am I missing a setting somewhere, I have checked everywhere I can think of. 

Thanks,

**Comment by AwakeningNC** [comment]
I just updated to the 2.2 beta and don't see this fix or where I can customize my feed for this, please let me know. 

Thanks

**Comment by mbabker** [comment]
If you have a menu item for the RSS feed, you should check there for any limit options.  I'm not looking at the interface at the moment, but I think the only other fallback option if a limit isn't explicitly set is the global feed limit in your site's Global Configuration.
