### ISSUE TITLE
no podcast button for articles in backend - Joomla 3.3.6 - "modal-button" -> "btn modal-button"

### ISSUE THREAD

**Issue by 2afs** [BabDev/Podcast-Manager#193]
Dear all,
i'm fighting with the following issue:
no podcast button for articles in BACKEND- in the frontend it works fine

where to change "modal-button" -> "btn modal-button" (see picture 1)???

configuration:
Database Version	5.1.36
Database Collation	utf8_general_ci
PHP Version	5.3.29
Web Server	Apache
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

![2015-01-11 15_04_10-joomla 3 test - administration - article manager_ edit article](https://cloud.githubusercontent.com/assets/10486185/5695426/624feacc-99a3-11e4-9a06-e6f1f35fe128.png)

![2015-01-11 15_07_38-home](https://cloud.githubusercontent.com/assets/10486185/5695437/fd293120-99a3-11e4-8f92-234c29e8b1da.png)

**Comment by mbabker** [comment]
This is already fixed in the code (https://github.com/BabDev/Podcast-Manager/commit/507ae1a1d0340c9ead1441d2e7d94571a03eac04) and will be in the next release.
