### ISSUE TITLE
Feed didn't update after episode #20

### ISSUE THREAD

**Issue by KellenBurns122** [BabDev/Podcast-Manager#194]
Michael,

Have a podcast with 28 episodes uploaded but the feed I created didn't update after episode 20.  21-28 never made it to the feed.  

http://r-rmediagroup.net/component/podcastmanager/?format=raw&feedname=1

Can you help me diagnose?

**Comment by mbabker** [comment]
It's a known issue from the last release.  https://github.com/BabDev/Podcast-Manager/issues/190 can show you some workarounds while I finalize the new release.
