### ISSUE TITLE
iTunes Podcasts Limited to 20 Tracks

### ISSUE THREAD

**Issue by UKDavid** [BabDev/Podcast-Manager#195]
I've found that I cannot publish a track on iTunes once the list reaches 20 tracks, so new ones only show up when I first un-publish old ones, so that the list never exceeds 20 tracks. Is this an issue with iTunes or with Podcast-Manager? If it's Podcast-Manager how can I remove/adjust the limit?

**Comment by mbabker** [comment]
It's a known issue.  See https://github.com/BabDev/Podcast-Manager/issues/190 for some tips while I finalize the next release.
