### ISSUE TITLE
How can i see the # of clicks en each podcast?

### ISSUE THREAD

**Issue by jcveramartin** [BabDev/Podcast-Manager#196]
How I can see the number of clicks that each podcast?

I wonder what is each one of my podcast, but do not know how I can see the number of plays or downloads. Can you help me?

thx

**Comment by mbabker** [comment]
In the admin configuration there is support for third party tracking systems (currently [blubrry](https://www.blubrry.com/) and [Podtrac](http://podtrac.com/)).  You can register with one of these providers and set the necessary configuration options to use them for your tracking.
