### ISSUE TITLE
rss-feed shows not all podcasts

### ISSUE THREAD

**Issue by kai2** [BabDev/Podcast-Manager#197]
Hi,
I´m running Joomla 3.3.6 with Podcast Manager 2.1.0. 
The RSS-Feed shows only a part of my older Podcasts in e.g iTunes or Feedly.
Any idea why?
Thanks
Kai-Uwe

**Comment by mbabker** [comment]
It's a bug in that release.  Please use the 2.2 beta release.

**Comment by kai2** [comment]
Where can I download this version?

**Comment by mbabker** [comment]
https://www.babdev.com/extensions/releases/podcast-manager-developer-release/ver22_BETA

**Comment by kai2** [comment]
Thank you :-)
