### ISSUE TITLE
Statistics on RSS Feed, Associated Podcasts

### ISSUE THREAD

**Issue by xylopolist** [BabDev/Podcast-Manager#198]
Hello,

I enjoy using your component and had no issues with set-up, etc. Thanks very much - planning on buying you a beer! :)

Just wondering if there is anything already in place to track any sort of statistics from the RSS feed and/or amounts of plays from the embedded players on my site coming in via the module?

Thanks,
David

**Comment by mbabker** [comment]
Within the extension, there aren't any stats gathering routines in place.  However, there is support for third party tracking systems (currently [blubrry](https://www.blubrry.com/) and [Podtrac](http://podtrac.com/)).  You can register with one of these providers and set the necessary configuration options in the admin configuration to use them for your tracking needs.

**Comment by xylopolist** [comment]
Thank you very much for the information - I have registered with blubrry and will continue to use Podcast Manager. They have provided a redirect in order to start collecting stats on the feed (http://media.blubrry.com/drinkfivenetwork/www.example.com/path/to/media.mp3). Where can I insert this redirect in the admin side of Podcast Manager to make all of this work? Will simply selecting blubrry in the stat tracking dropdown take care of this automatically?

Thanks again,
David

**Comment by xylopolist** [comment]
I was able to get it to work. Thanks for your help and for developing this very useful component.

David

**Comment by mbabker** [comment]
If you have the option enabled, Podcast Manager takes care of adding the relevant extra stuff.

**Comment by SplitHops** [comment]
Hi guys, I have created a successful bluburry account and am seeing my link is working 
https://www.blubrry.com/chefjamie/  I am just not sure now how to add this to my podcast manager feeds.  Here is what I have in the feed url now:

https://www.blubrry.com/chefjamie/www.chefjamie.com/media/podcasts/Food-Wine-Podcasts/  I am not sure how this is working can yo help me out xylopolist
