### ISSUE TITLE
Joomla 3.4 breaks Podcast Manager Content Plugin

### ISSUE THREAD

**Issue by jthrongard** [BabDev/Podcast-Manager#199]
Tested using 2.2Beta, no error messages, just no podcast player in content.

**Comment by mbabker** [comment]
Can you enable logging in the component's params and check for any notes in `<log_path>/podcastmanager.php`?  I have things coded to log most errors there versus error messages displayed on the site.

**Comment by jthrongard** [comment]
I really can't since this is on a live site and I just launched an episode
today so I need to have people be able to access it. Right now we are
running Joomla 3.3.6 so the plugin stays up. Is there a way we can test on
a dev site?

**Comment by mbabker** [comment]
Sure.  You should be able to backup the site to a dev environment and update it to 3.4.1.  I'll see if I can reproduce the problem locally too, but any error from a live or dev system definitely helps.

**Comment by mbabker** [comment]
I did some testing on my local setup with Joomla 3.4.1 and Podcast Manager 2.2 Beta using PHP 5.4, 5.5, and 5.6 (to eliminate any possible issue with that) and I couldn't get an error to occur.
