### ISSUE TITLE
Podcast Manager not working in back end

### ISSUE THREAD

**Issue by nickstarbright** [BabDev/Podcast-Manager#201]
Hi, I appear to be having an issue getting the podcast manager v2.1.0 to work properly.

I'm running Joomla 3.4.1. When I go into the Components> Podcast Manager> Administration Panel> Podcast: When I make a selection of some of the test files I've uploaded, in a sample feed, the buttons at the top such as Edit, Publish, Unplublish, Check-In, Trash, and Batch do not appear to be working. 

I've enabled all necessary plugins and when I click on them, I get no response. Every other tab such as Feeds, File Manager, the buttons at the top on those pages work. 

Here's a screenshot of what I'm talking about
![fireshot screen capture 4](https://cloud.githubusercontent.com/assets/10357913/7218305/b38c45e6-e61c-11e4-926b-c3f9bf7ca2b4.png)

What should I look at to troubleshoot and get working properly?

Thank You for your assistance in Advance!

**Comment by mbabker** [comment]
It's a known issue that's been fixed.  You can use the 2.2 beta release on
my site to get that and several other bug fixes.

**Comment by nickstarbright** [comment]
@Mbabker Thank you sir! 

I have installed the update and everything is working as expected!

I'm buying you a beer! 

Again thank you!
