### ISSUE TITLE
RSS Feed Issues, iTunes, date sort, 20 item limit

### ISSUE THREAD

**Issue by bwflinn** [BabDev/Podcast-Manager#204]
We're running several podcasts from our site and theyre all having problems updating in iTunes.

First problem is some feeds list each podcast item oldest to newest and some sort new to old.

New to old...
http://sports56whbq.com/index.php/component/podcastmanager/?format=raw&feedname=4

Old to new...
http://sports56whbq.com/index.php/component/podcastmanager/?format=raw&feedname=5

The feeds need to sort New to Old for iTunes to show them in order.

And all of our feeds are only showing 20 items per feed even though we have uploaded more that 20 podcasts for each feed.

**Comment by mbabker** [comment]
Please test with the 2.2 Beta available from my website; these issues
should all be addressed.

**Comment by bwflinn** [comment]
Thank you for quick response!  I have downloaded the latest from (https://github.com/BabDev/Podcast-Manager) but how do I install it in Joomla?  The normal Joomla Installer gives these errors...



Error
Archive does not exist

Warning
JFolder: :files: Path is not a folder. Path: /chroot/home/flinncom/sports56whbq.com/html/tmp/install_553e7031b7336/Podcast-Manager-master/packages/install_553e7031d9589

JFolder: :folder: Path is not a folder. Path: /chroot/home/flinncom/sports56whbq.com/html/tmp/install_553e7031b7336/Podcast-Manager-master/packages/install_553e7031d9589

JFolder: :files: Path is not a folder. Path: /chroot/home/flinncom/sports56whbq.com/html/tmp/install_553e7031b7336/Podcast-Manager-master/packages/install_553e7031d9589

JInstaller: :Install: Cannot find Joomla XML setup file

Update path does not exist

Package Update: There was an error installing an extension: com_podcastmanager.zip

Message
Error installing component

**Comment by mbabker** [comment]
You have to get the prepared package from
https://www.babdev.com/extensions/latest

**Comment by bwflinn** [comment]
Thansk!!  I've installed 2.2.. so far so good.. I will check iTunes again later to confirm

**Comment by packerprogrammer** [comment]
Thanks for the update. I was able to search for this issue and download 2.2 which fixed my issue before I even asked! Thanks!
