### ISSUE TITLE
Parse Metadata isn't working when adding new podcasts in 2.2 beta

### ISSUE THREAD

**Issue by xylopolist** [BabDev/Podcast-Manager#205]
Hello, I'm having an issue where - after upgrading to the 2.2 beta - metadata from podcasts does not automatically populate into the associated fields, and clicking on the new 'parse metadata' button doesn't do anything. Here is the link associated with the button right now: 

/administrator/index.php?option=com_podcastmanager&view=podcast&layout=edit# 

Any idea how to get this functionality up and running again? It makes it a lot easier to add podcasts if most of the fields are populating automatically from the metadata already present.

Thanks,
Dave

**Comment by sbtecharts** [comment]
I'm also having this issue after upgrading to 2.2

**Comment by mbabker** [comment]
The only way I can think it wouldn't work is if there were other JavaScript errors when loading the page (this was something I tested a few times before tagging the release on both Joomla 2.5 and 3.4).  Can you check your browser's development console (Chrome Dev Tools or Firefox Web Console for example) and see if there are any errors?

**Comment by sbtecharts** [comment]
When going in to follow up on it today it worked fine. Thank you for your quick followup.

**Comment by mbabker** [comment]
There is one caveat to this whole process (I forget if a message gets displayed).  Right now the parse function doesn't work with remote media.  The underlying parser library will only read local files and I haven't taken the time to write code that would download a remote resource, parse it, and remove the temp file.  So if you did try it with a remote file and it didn't work, that could be one reason (and I'll double check on whether it throws a message).

**Comment by mbabker** [comment]
There is a JavaScript error with PM 2.2 and Joomla 3.5 somewhat similar to this.  It's fixed in PM 3.0 dev branch (getting that stabilized).  So closing this item out since as best as I can tell with all the rewrites things are fine now.
