### ISSUE TITLE
PHP "Strict Standards" errors in Admin view

### ISSUE THREAD

**Issue by njbair** [BabDev/Podcast-Manager#209]
I'm running a fully up-to-date Joomla site with the latest Podcast Manager. I see these errors in the podcast edit view:

**Strict Standards**: Declaration of PodcastManagerModelPodcast::prepareTable() should be compatible with JModelAdmin::prepareTable($table) in **[...]/administrator/components/com_podcastmanager/models/podcast.php on line 27**

**Strict Standards**: Declaration of PodcastManagerTablePodcast::_getAssetParentId() should be compatible with JTable::_getAssetParentId(JTable $table = NULL, $id = NULL) in **[...]/administrator/components/com_podcastmanager/tables/podcast.php on line 314**

Is this a known bug?

**Comment by mbabker** [comment]
Yes.  Because the code supports Joomla 2.5 and 3.x, there are a few places
where there are messages like this displayed because of changes between the
two versions.  Nothing is broken.

**Comment by njbair** [comment]
Thanks. Glad to know nothing's broken. I guess those errors won't even show up in production with display_errors turned off.
