### ISSUE TITLE
Can't associating episodes with the feed (e.g. Getting Started)

### ISSUE THREAD

**Issue by badrenali** [BabDev/Podcast-Manager#212]
I'm able to create a feed (Podcast Manager: Feed), and to upload mp3 episode files (Podcast Manager: File Manager), but can't figure out how to associate the mp3 episode files with the feed.

Our Joomla install has all media under images, so we've set the default directory (for Podcast Manager: File Manger) as:
.../images/audio

Any suggestions? 
What step am I missing?

Podcast Manager 2.2.0
Joomla 2.5.16

**Comment by mbabker** [comment]
Have you created podcasts in the backend?  This is the last step needed to make it work; in this screen is where you set the file that's referred to by an episode and the metadata for it.

**Comment by mbabker** [comment]
Also, you shouldn't need to use a relative path for your `images/audio` folder.  With that convention, you'd be instructing Joomla to look for an images folder one level above the web root.  The default path is `media/com_podcastmanager` which doesn't include the relative `../`, so your path setting should be `images/audio` (all paths here are always relative to your site's root).

**Comment by badrenali** [comment]
Correct, the path wasn't typed in as relative. 

Creating podcasts in the backend is probably what I'm missing. I'm pretty new to Joomla. 
Do you mean creating a Category named Podcast, then each episode would be an Article of that Category?
I can do that, but I'm not clear on how to set the file that is referred to by an episode. If I click the "podcast" button, there are no files to choose from because they haven't yet been associated with the feed.

Is there someplace I can find a quick step by step for how to do this?

**Comment by mbabker** [comment]
In the Podcast Manager component there's a "Podcast" submenu item (between the files and file manager items), that's where you add your podcasts.

**Comment by badrenali** [comment]
Ah, somehow I missed the "new" button on that screen, and just couldn't figure out how to do anything with it.  Thanks for your help!  I think I'm up and running now...  :-)
