### ISSUE TITLE
Path error on opening Feed list page

### ISSUE THREAD

**Issue by GrannyKat** [BabDev/Podcast-Manager#214]
When a user first tries to open a feed listing menu item, error message appears:

Cannot resolve path, path seems invalid: `/media/mediaelements/css/../../../../../Downloads/johndyer-mediaelement-d799a54/build/skipback.png`

The file skipback.png is actually in /media/mediaelements/css/skipback.png where it belongs. Then it gets weirder -- when user returns to home page and reselects same menu item, the page opens correctly. How can I fix?

**Comment by mbabker** [comment]
Donwload the file from https://raw.githubusercontent.com/BabDev/Podcast-Manager/f0a55e6cb14bc13ce8589706a3142890c9385418/plg_content_podcastmanager/mediaelements/css/mediaelementplayer.min.css and place it at `media/mediaelements/css/mediaelementplayer.min.css`.  Apparently copying files around on my laptop managed to cause something to auto-update.
