### ISSUE TITLE
Extension Download problem in Joomla 3.4.4

### ISSUE THREAD

**Issue by jshirey34** [BabDev/Podcast-Manager#215]
When trying to download from the extension downloader from Joomla 3.4.4 i get a warning and error message trying to install this extension: https://www.babdev.com/extensions/releases/podcast-manager/podcast-manager-2-2-0/pkg_podcastmanager_2-2-0-zip?format=raw&jcompat=my.zip

says SSL certificate can't be found and has an invalid URL. Please help me fix. Thanks - John

**Comment by mbabker** [comment]
The SSL certificate issue may be related to Joomla.  Ultimately, that URL redirects to the download store here on GitHub who uses Amazon S3 for the files.  S3 still has an older SSL certificate that is signed with a weaker certificate and the root certificate pack with Joomla does not include these weak signatures anymore (the same issue exists with com_weblinks for the same reason).

You can follow that URL which will download the package to your local system then you can install the package to Joomla as an upload.

**Comment by jshirey34** [comment]
thanks! I got it. Appreciate the help
