### ISSUE TITLE
Add podcast from front end

### ISSUE THREAD

**Issue by kerryrodtnick** [BabDev/Podcast-Manager#224]
I'm having trouble getting a menu option to add a new podcast from the front end to work.  I want it set up that a certain level user can add a new podcast.  I have the menu item showing.  But when i click on the item, it gets a 403 (not authorized) error and cannot open the page.  I feel I have the permissions set correctly.  What am I missing?

**Comment by mbabker** [comment]
I can't say I've tested this lately but before the last release it was OK.
I'm in the middle of rebuilding everything for Joomla 3.5+ and dropping a
lot of old workarounds for 2.5+ support, so I can't say with certainty what
is or isn't working now but in the next couple of weeks I'm trying to have
the first builds of the cleaned up code ready.

**Comment by sdawomyn** [comment]
Please unsubscribe me from this email.

Jacqueline Hegarty, Web Designer

Hegarty Services

(510) 263-0274

**Comment by kerryrodtnick** [comment]
Thank you for responding. I did get it to work by making the menu item "public" access. I think it's a permissions thing in my side. 

Thank you for making this module. It is very helpful and does almost everything I want it to do. I've been able to style it like my site very easily.

**Comment by mbabker** [comment]
Just for reference I went through and did a couple of quick tests.  From my perspective things are working right as it's all using Joomla's ACL system.  For a guest user they'll correctly get a 403 page and a super admin gets the edit form.  I didn't try too many other scenarios in between, but as you suggested, ultimately I think it's coming down to your site's permissions.
