### ISSUE TITLE
Error code 500

### ISSUE THREAD

**Issue by mcapranos** [BabDev/Podcast-Manager#225]
I've been using podcast manager for a while now, and it's worked flawlessly for my site. 
However, I noticed yesterday that an article with a podcast in it, doesn't load. 

I'm getting error code 500 "currently unable to handle this request."

Removing the {podcast ...} tag the article displays fine. 
I confirmed that the podcasts are still there. I was making changes to my .htaccess file recently, but I removed the file to test, and the issue was still present. 

Any recommendations for things I can check? 

Thanks!

**Comment by mbabker** [comment]
Turn on logging in the component's options.  Most errors should be getting caught in the content plugin that converts that tag into the correct output and logged to a file at `logs/podcastmanager.php`.  Unfortunately the plugin still uses Joomla 2.5 style error checks, so if the query in that plugin is failing on a 3.x environment it may be bubbling an Exception up and blocking the page from rendering (in which case you'd need to turn on debug mode & set error reporting to development to get maximum error data).

**Comment by mcapranos** [comment]
The joomla site is still joomla 2.5, 

I am seeing error messages, here's a snippet of what's in the log. 

2016-03-23T00:53:53+00:00       WARNING deprecated      JRegistry::getValue() is deprecated. Use get instead.
2016-03-23T00:54:02+00:00       WARNING deprecated      JDate::toFormat() is deprecated.
2016-03-23T00:54:02+00:00       WARNING deprecated      JDatabase::getErrorNum() is deprecated, use exception handling instead.
2016-03-23T00:54:02+00:00       WARNING deprecated      JDatabase::getEscaped() is deprecated. Use JDatabase::escape().

**Comment by mbabker** [comment]
None of those are errors.  Deprecation messages just say that some function being called won't be there later, and that's all internal to Joomla versus something I'm explicitly using.

**Comment by mbabker** [comment]
If it's just the one article, try putting the {podcast} marker back in it and disabling the Podcast Manager content plugin.  If that one article still errors with the plugin turned off, that should be a clue that another plugin (probably one in order before the Podcast Manager plugin in the content group) could be causing a conflict.

**Comment by mcapranos** [comment]
With podcast manager plugin disabled, the articles with {podcast id=x} are now being displayed, if I re-enable the plugin, I'm getting the error 500.

**Comment by mcapranos** [comment]
I checked through my website logs and the logs for my joomla site again, nothing in there indicating any issues.

**Comment by mbabker** [comment]
Without some other kind of error info it's hard to say.  If it's Joomla's 500 error page with error reporting and debug turned on you should get some kind of error detail.  If it's the web server's 500 error page, it may be something else (I'm not quite sure what off the top of my head but the plugin definitely shouldn't cause that to happen under normal use).

**Comment by mbabker** [comment]
If you can, post here the article's contents from the database.  Maybe one of the checks hits an odd condition that causes some kind of other failure.

**Comment by mcapranos** [comment]
I'll try to get it, my mysql is terrible at best. 
Give me a few minutes to see what I can do, 
Thanks!

**Comment by mcapranos** [comment]
The 500 error is only present for articles that have a podcast in them, all articles work and display fine, no other issues one the site. If I remove the {podcast } tag from the article it displays without issue. 

For the directory where the podcasts are saved, what file permissions should be on the directory? 

I have no idea how to get just one articles from mysql, sorry : /

**Comment by mbabker** [comment]
The media/com_podcastmanager directory should have 755 permissions on the directory and all files have 644, same as the rest of Joomla.

You should be able to just copy the contents of the `introtext` and `fulltext` columns in the database.  The other option is copy the article's HTML from the Joomla admin.  I mainly just need it unmodified (which is the state it'll be in when plugins start processing stuff).

**Comment by mcapranos** [comment]
Here's the html from the article: 

``` html
<p style="text-align: center;"><img src="images/audio/flynns_arcade_002/kOCjhA1421780981.png" border="0" width="500" height="500" style="border: 0;" /></p>
<hr id="system-readmore" />
<p style="text-align: center;"> </p>
<p style="text-align: center;">{podcast id=2}</p>
<p style="text-align: justify;"><strong>The second episode of Flynn's Arcade tackles the super human brutality of Injustice: Gods Among Us, a game that manages to make Aquaman cool. Is it the superhero fighting game we deserve, or the superhero fighting game we need right now?</strong></p>
<p style="text-align: justify;"><strong><br /></strong>Feedback? Hate mail? send it to jflynn@gaming-media.com!</p>
<h1 style="text-align: left;"><a href="https://twitter.com/Modern_Robot" target="_blank">Follow @Modern_Robot on Twitter</a></h1>
<h1 style="text-align: left;"><a href="https://player.me/modern_robot" target="_blank">Or on player.me</a></h1>
<p style="text-align: justify;"> </p>
```

**Comment by mbabker** [comment]
What other extensions do you have loaded?  It looks like you have something that's compressing output and adjusting the paths for your images?

Also, what happens if you reorder the plugins in the content group?  Try ordering the Podcast Manager plugin before all other content plugins to see if there's perhaps a conflict with the run order of the plugins (I've seen this happen in a couple of odd situations with some plugins in general, just one of those quirks).

I'll have to think on this a little more to see if I can come up with some solution.  For now though it seems like there's some sort of environmental issue at play here and the Podcast Manager plugin doesn't play well with one of the other extensions on the site.

**Comment by mcapranos** [comment]
I have a plugin that resizes and creates thumbnails for my article images, the path would probably be to the cache directory. 

I put the {podcast tag} to the top of the article, no luck,

**Comment by sdawomyn** [comment]
Please remove me from this mailing list as my client who was using podcast manager has switched to a WordPress platform with a different podcast app.

**Comment by mbabker** [comment]
> I have a plugin that resizes and creates thumbnails for my article images, the path would probably be to the cache directory.
> 
> I put the {podcast tag} to the top of the article, no luck,

No, I'm suggesting in the Plugin Manager to re-order the content plugins so that the Podcast Manager plugin is the first one to execute in the content group.

**Comment by mbabker** [comment]
@sdawomyn You need to log into GitHub and unstar and unwatch this repository.  Once logged in, navigate to https://github.com/BabDev/Podcast-Manager and you should see the appropriate buttons at the top right corner of the page.  There isn't a mailing list I can manage on this repository, sorry.

**Comment by mcapranos** [comment]
Just tried re-ordering the plugins to make sure podcast manager was number 1, same results, a page with a the podcast tag won't load.

**Comment by mcapranos** [comment]
mbabker, thank you for all the assistance, 
I've been straddling bandwidth limits where I host my site, so I've decided to sign up for a podcast service, and will embed the audio into my articles. 

When I start up another site, if there's less traffic to it, I'll be sure to try podcast manager again, because it's too damn good of an add on not to use. 

Thanks again!
