### ISSUE TITLE
Podcast Feed not working

### ISSUE THREAD

**Issue by abiade** [BabDev/Podcast-Manager#226]
Hello all,
My podcast feed xml looks good, but won't validate on itunes podcast connect. Kindly help me out http://restorationhousenj.org/component/podcastmanager/?format=raw&amp;feedname=2

**Comment by mbabker** [comment]
Feed ID 2 is empty, but feed ID 1 has content.

Your site's in offline mode, which causes Joomla to send a HTTP 503 header instead of HTTP 200.  This will cause any system to think it can't connect to the feed because of the non-200 header.  When you put your site online it will be fine.
