### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by florantevaldez** [BabDev/Podcast-Manager#228]
I'm testing the plugin on a demo site and have successfully created a feed, however, I'm having isse with the audio not playing when I click the play button. 

Can you help: test site is: https://florante.demojoomla.com/index.php

**Comment by mbabker** [comment]
According to my browser's console, it won't load the video because your HTTPS (secure) site is requesting the video from a HTTP (non-secure) source... http://cl.ly/0s2d3P123E3m

**Comment by florantevaldez** [comment]
Thank you for your reply. That's interesting because I've uploaded the file in the media directory of the same site, it's not like an external URL so the file has to be https too, right? Am I missing anything? 
![2016-06-03_20-54-34](https://cloud.githubusercontent.com/assets/19722559/15779191/738de36e-29cd-11e6-8ce2-da255a82f2f5.png)

**Comment by mbabker** [comment]
It looks like you turned on the Blubrry tracking service which is why it's coming from an external URL.  Try turning that off and see what happens (component config).

**Comment by florantevaldez** [comment]
Awesome! That solved the problem. Thank you.
