### ISSUE TITLE
"use up/down arrow" text overlapping media player

### ISSUE THREAD

**Issue by baronvongrant** [BabDev/Podcast-Manager#229]
My site updated and now the media player has text overlapping the player. Here is a page where you can see the issue: http://thetvdudes.com/index.php/features/podcasts/564-the-tv-dudes-podcast-084-comics-issues. Wondering if anyone knows how I might fix this.

**Comment by mbabker** [comment]
At a quick glance I don't see where the conflict is but it seems like some CSS or maybe something in the player's JavaScript is not applying correctly.  Try scanning https://github.com/johndyer/mediaelement/issues for possible leads.

**Comment by baronvongrant** [comment]
Cool. Thanks. I found this, which helped:
https://github.com/johndyer/mediaelement/commit/374e957cfb6b6b7255f50f844bf94a5a73b55d7f

 Now it is just the scrubber/slider which isn't working.
