### ISSUE TITLE
Feed Listing Module Order

### ISSUE THREAD

**Issue by jeffdockum** [BabDev/Podcast-Manager#235]
I suppose it's more of a feature request than an issue. Is it possible to control the sort order of podcasts in the Feed Listing module? 

I've re-created a collection and set the podcasts "created" dates, but did not adjust the "publish" dates. I wanted the newest to appear at the top. 

I figured out that if I set the publish dates, it works that way, but would be nice again to choose what date value it sorts on. Maybe this is something you have worked on for the 3.0 branch, or could add it?

**Comment by mbabker** [comment]
Done.  https://github.com/BabDev/Podcast-Manager/commit/c7d585cef2bd7c930b663d4061d63813775a44b3
